### PR TITLE
updated to add /usr/local prefix

### PR DESCRIPTION
**Pull request by leancode**

### CODE REVIEW

**Comment by timiwahalahti** [comment]
@leancode Could you please explain the reason for this change? Thank you!

**Comment by rollecode** [comment]
No explanation, so closing this.

**Comment by leancode** [comment]
Sorry I missed this message. The reason was to be more accurate for homebrew installs of nginx on macos. The /etc/nginx/sites-enabled/sitename.test is clearly wrong for a homebrew installed lemp. The patch just changes it to the actual location /usr/local/etc/nginx/sites-enabled/sitename.test

**Comment by rollecode** [comment]
@leancode Everything is linked under /etc/nginx because of consistency (it's the default on Linux and the default on most of the servers). See [this bit](https://github.com/digitoimistodude/macos-lemp-setup/blob/af589e7fe8ca1766746762e83838674f8bb2f303/install.sh#L26).

**Pull request closed without merging**
