### PR TITLE
Add instructions on how to install Redis

### PR DESCRIPTION
**Pull request by timiwahalahti**

### CODE REVIEW

**Review by rollecode — CHANGES_REQUESTED** [review]
Add some kind of note that `brew update` needs to be run before brew install command, otherwise returns:

curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "redis"

**Comment by rollecode** [comment]
All steps except last one go through fine. For some reason getting:

``` shell
$ php -r "if (new Redis() == true){ echo \"\r\n OK \r\n\"; }"

Fatal error: Uncaught Error: Class 'Redis' not found in Command line code:1
Stack trace:
#0 {main}
  thrown in Command line code on line 1
```

And then again tested if something wrong with install but no, it is present:

``` shell
$ pecl install redis-5.0.2

pecl/redis is already installed and is the same as the released version 5.0.2
install failed
```

Also the step 6 should tell what should happen after that command, what kind of message should be shown, "OK" right? It's obvious, but add something like if you get OK it's all OK, if not, do this... 

nginx has been restarted and even tested restarting php@7.2 and php@7.3 services, didn't change the error message.

**Comment by timiwahalahti** [comment]
Checked with @ronilaukkarinen on Slack about the installation problems and solved those out. Updated instructions accordingly.

Roni can you give one final look before the merge. Thanks!

**Comment by rollecode** [comment]
> Checked with @ronilaukkarinen on Slack about the installation problems and solved those out. Updated instructions accordingly.
> 
> Roni can you give one final look before the merge. Thanks!

Looking good, go ahead! 👍

**Pull request merged**
